### PR TITLE
Add support for the new light device category added in the Starling v2 API for Issue #99

### LINKED ISSUE #99: Add support for floodlight control on relevant cameras
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ThomasLomas/ha-starlinghomehub/issues?q=is%3Aissue+label%3A%22enhancement%22).

### Is your feature request related to a problem? Please describe.

StarlingHub exposes floodlight control for the "Nest Cam with Floodlight (2nd generation)" device, but it's not available for control via this integration and no mention of it on the checklist of current+pending supported features.

### Describe the solution you'd like

Add switch control for the floodlight on these cameras. The field name is "floodlightOn" per the [latest API docs](https://sidewinder.starlinghome.io/sdc/?_gl=1*gact0e*_gcl_au*MTM5NzEyNzAyLjE3MzQzMjMzNjQ.*_ga*MTAzMDEwNjEyNC4xNzM0MzIzMzY1*_ga_RB2T845B29*MTczNDMyMzM2NS4xLjEuMTczNDMyMzg5Ni4zNS4xLjkxOTc3MTcx#camera:~:text=close-,floodlightOn,-Boolean)

### Describe alternatives you've considered

Use the direct homekit integration instead.

### Additional context

Happy to help with testing and debugging as a fellow SWE!

### PR DESCRIPTION
**Pull request by binarydev**
Fixes #99. Based on v2 API docs last updated on Dec 3rd, 2024, API Level 3.3, using firmware v2024.51.3.
[starling-api-local-reference.zip](https://github.com/user-attachments/files/18254736/starling-api-local-reference.zip)

Adds support for the light device category, and I've confirmed that it works with Google Home's floodlight devices along with any 3rd party lights exposed by the Starling API. It supports turning the lights on and off, as well as setting the brightness, rgb color, and color temperature for lights that support doing so.

### CODE REVIEW

**Comment by ThomasLomas** [comment]
Thanks! I am preparing an upcoming release to better support the wider range of devices now available so will review and pull it in to that

**Comment by binarydev** [comment]
That's awesome, and I appreciate you taking a look! I'm happy to assist with testing of the new release if that's helpful as well at some point. Hope you have a happy new year!

**Comment by ThomasLomas** [comment]
> That's awesome, and I appreciate you taking a look! I'm happy to assist with testing of the new release if that's helpful as well at some point. Hope you have a happy new year!

Appreciate that! I just pushed up v1.2.0 as a pre-release. You should be able to manually select this version in HACS and that features your changes (along with some other stuff)

**Comment by binarydev** [comment]
v1.2.0-rc works wonderfully! thanks for cutting the pre-release for testing 🎉  fyi for thermostats I believe there's a sensor name with a typo: 
Screenshot 2024-12-27 at 1 18 59 AM

Marking this PR as closed now. Cheers 🍻

**Comment by ThomasLomas** [comment]
> v1.2.0-rc works wonderfully! thanks for cutting the pre-release for testing 🎉 fyi for thermostats I believe there's a sensor name with a typo: Screenshot 2024-12-27 at 1 18 59 AM
> 
> Marking this PR as closed now. Cheers 🍻

oops thanks!

**Pull request closed without merging**
